# WandB Sweep Configuration for Deep Learning Experiment
# program: train_fashion_10.py
# project: "Deep_learning_project"
# entity: "s224225"

# Sweep Configuration
method: bayes  # Options: grid, random, bayes
metric:
  name: val_accuracy
  goal: maximize

# Parameter Search Space
parameters:
  num_epochs:
    value: 75
  
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  
  batch_size:
    values: [32, 64, 128, 256]
  
  optimizer:
    values: ["adam", "sgd"]
  
  l2_coeff:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  
  n_hidden_units:
    values: [
      [256, 128],
      [512, 256, 128],
      [1024, 512, 256],
      [512, 256, 128, 64],
      [1024, 512, 256, 128, 64]
    ]
  
  activation:
    values: ["relu", "tanh"]
  
  # weights_init:
  #   values: ["xavier", "he", "normal"]
  
  loss:
    value: "cross_entropy"  # Fixed parameter